volumes:
  pf_pg_data_production:
  pf_static_volume:
  pf_media_volume:
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pf_pg_data_production:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pf_lasellar -d portfolio" ]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    image: lasellar/portfolio_backend
    env_file: .env
    volumes:
      - pf_static_volume:/backend_static
      - pf_media_volume:/app/media/
    depends_on:
      db:
        condition: service_healthy
  gateway:
    image: lasellar/portfolio_gateway
    env_file: .env
    volumes:
      - pf_static_volume:/backend_static/
      - pf_media_volume:/app/media/
    ports:
      - 8080:80
    depends_on:
      - backend

networks:
  default:
    name: pf_bridge_network
    driver: bridge