# Generated by Django 5.1.6 on 2025-02-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_commercial',
            field=models.BooleanField(default=False),
        ),
    ]
