# Generated by Django 5.1.6 on 2025-02-20 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_is_commercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('modelmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.modelmixin')),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('url', models.URLField(blank=True)),
            ],
            bases=('main.modelmixin',),
        ),
    ]
