# Generated by Django 5.1.6 on 2025-02-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_projectskill_project_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(related_name='projects', through='main.ProjectSkill', to='main.skill'),
        ),
    ]
